INSERT INTO ROLE(role_name) VALUES('ADMINISTRATOR');
INSERT INTO ROLE(role_name) VALUES('CUSTOMER_USER');
INSERT INTO ROLE(role_name) VALUES('SALE_USER');
INSERT INTO ROLE(role_name) VALUES('SECURE_REST_API');
