INSERT INTO ITEM_GROUP(group_name) VALUES('HEALTH_BEAUTY');
INSERT INTO ITEM_GROUP(group_name) VALUES('SPORTS');
INSERT INTO ITEM_GROUP(group_name) VALUES('FASHION');
INSERT INTO ITEM_GROUP(group_name) VALUES('ELECTRONICS');